// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "swift-zinnia-forge-app-snack-studio",
      "namespace": "wingman-apps",
      "script": "bun",
      "args": [
        "/app/src/apps/app-runner.ts",
        "--app-id",
        "2c3dc1d5-308a-4457-924e-112a16a96caa",
        "--app-label",
        "Snack-Studio",
        "--app-root",
        "/workspace/code/snack-studio",
        "--start-script",
        "bun run start",
        "--user-alias",
        "swift-zinnia-forge",
        "--port",
        "42009"
      ],
      "cwd": "/workspace/code/snack-studio",
      "env": {
        "WINGMAN_PROCESS_KIND": "user-app",
        "APP_ID": "2c3dc1d5-308a-4457-924e-112a16a96caa",
        "USER_ALIAS": "swift-zinnia-forge"
      },
      "out_file": "/workspace/code/snack-studio/apps/logs/swift-zinnia-forge-app-snack-studio-out.log",
      "error_file": "/workspace/code/snack-studio/apps/logs/swift-zinnia-forge-app-snack-studio-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
